version: "3.9"
services:
  sealwlapi:
    build: ../
    ports:
      -"3000:3000"
    links:
      -mongodb
  mongodb:
    image: mongo
    ports:
      -"27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME: eskenderdev
      - MONGO_INITDB_ROOT_PASSWORD: eskenderdev 
    volumes:
      - mongo-data:/data/db
  volumes:
    mongo-data:
