version: "3.9"
services:
  sealwlapi:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    links:
      - mongodb
    volumes:
      - ../:/home/app
    mongodb:
      image: mongo:4.4.12
      # If you want to expose these ports outside your dev PC,
      # remove the "127.0.0.1:" prefix
      ports:
        - 127.0.0.1:27017:27017
      volumes:
        - ~/volumes/seal-wl/mongodb/:/data/db/
      environment:
        - MONGO_INITDB_ROOT_USERNAME=dev
        - MONGO_INITDB_ROOT_PASSWORD=dev
